from yacs.config import CfgNode as CN

_C = CN()
# DATASET CONFIG
_C.DATASET = CN()
_C.DATASET.ROOT = '.'
_C.DATASET.CSV = 'train.csv'
_C.DATASET.TRAIN_DIR = 'train'
_C.DATASET.TEST_DIR = 'test'

# MODEL CONFIG
_C.MODEL = CN()
_C.MODEL.NAME = 'fasterrcnn_resnet50_fpn'

# TRAINING CONFIG
_C.TRAIN = CN()

_C.TRAIN.LR_FACTOR = 0.1
_C.TRAIN.LR_STEP = [70, 90]
_C.TRAIN.LR = 0.001

_C.TRAIN.OPTIMIZER = 'adam'
_C.TRAIN.MOMENTUM = 0.9
_C.TRAIN.WD = 0.0001
_C.TRAIN.NESTEROV = False
_C.TRAIN.GAMMA1 = 0.99
_C.TRAIN.GAMMA2 = 0.0

_C.TRAIN.BEGIN_EPOCH = 0
_C.TRAIN.END_EPOCH = 100

_C.TRAIN.RESUME = False
_C.TRAIN.CHECKPOINT = ''

_C.TRAIN.IMAGES_PER_GPU = 8
_C.TRAIN.SHUFFLE = True